# Generated by Django 5.2.7 on 2025-11-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.IntegerField(blank=True, db_column='transactionID', null=True)),
                ('customerid', models.IntegerField(blank=True, db_column='customerID', null=True)),
                ('productid', models.IntegerField(blank=True, db_column='productID', null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.IntegerField(blank=True, null=True)),
                ('transdate', models.DateField(blank=True, db_column='transDate', null=True)),
            ],
            options={
                'db_table': 'transaction_detail',
                'managed': False,
            },
        ),
    ]
